
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.252.10.63)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=MPAY)(SERVER=DEDICATED)))
spring.datasource.username=msocial
spring.datasource.password=msocial2015
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.hibernate.ddl-auto=update

ftp.server=10.252.10.149
ftp.port=21
ftp.username=ftpuser
ftp.password=123456a@
ftp.filepath=/home/ftpuser/msocial/OCSSP_dump_OCSGW_20_05_2024.txt